### ISSUE TITLE
No remove_overrides() method in statsig to enable better unit testing

### ISSUE THREAD

**Issue by yawhide** [statsig-io/python-sdk#11]
hello,

there is no way to remove overrides which leaves to overrides from one of my test case to leak into all the other test cases. This leads to potential flakiness.

I noticed the javascript sdk has this functionality.
<img width="1175" alt="image" src="https://user-images.githubusercontent.com/5014112/197287444-514c41b5-9032-4091-a2ca-2dcedef30882.png">

Is this something we can add?

thanks

**Comment by tore-statsig** [comment]
Looks like we overlooked that when adding overrides, we can definitely add that.  Thanks for pointing this out!

**Comment by jkw-statsig** [comment]
@yawhide  we have a PR up for this now, will have a new version with remove apis for you early next week.
