### ISSUE TITLE
Overriding layers in local mode to enable testing

### ISSUE THREAD

**Issue by seamuswn** [statsig-io/python-sdk#19]
My team are currently evaluating the use of 'Layers' in our tech stack, but we don't see an obvious way to test locally with layers in our Python backend.

There are existing override methods present for gates, configs and experiments, but no equivalent method that I can find for layers.

Is there an existing pattern for testing layers?

**Comment by daniel-statsig** [comment]
Sorry for the delay here. This has now been added and is in v0.21.0.

- https://github.com/statsig-io/python-sdk/releases/tag/v0.21.0
- https://pypi.org/project/statsig/0.21.0/
