### ISSUE TITLE
Bug: Feature Gate is not returning the correct result when using Stage environment

### ISSUE THREAD

**Issue by cintia-zago** [statsig-io/python-sdk#21]
When we set the options using the StatsigEnvironmentTier.staging variable, the SDK returns False, even when the gate is True. 

`StatsigOptions(tier=StatsigEnvironmentTier.staging)`

It looks like the variable has the value "staging", and the SDK expects "stage". This is manageable by passing "stage" directly, but I'd like to warn you about this and make sure that this is bug.

**Comment by vijaye-statsig** [comment]
Is it possible you created a custom environment? 

Cc: @daniel-statsig

**Comment by cintia-zago** [comment]
I don't think so. At least that wasn't the intention. I'm just using the SDK constant to set up the options and then call the initialize method.

**Comment by tore-statsig** [comment]
The SDK shouldnt expect "stage" unless that was the environment you configured to pass in the console.  Do you have a link to the gate where you noticed this issue?

**Comment by jtwillis92** [comment]
I'm also seeing a similar issue with a `dev` custom environment. I have several feature gates configured with a rule to pass everyone for the `dev` environment and they are all failing when called using the Python SDK unless the corresponding gate has been fully launched.
![image](https://github.com/user-attachments/assets/c6a28f11-6d70-43dc-9980-31f334bc6d38)

![image](https://github.com/user-attachments/assets/111407e8-def3-49e6-a7fd-196d5875f8a7)

But if I test the gate in the statsig UI with only the `dev` environment then it passes:
![image](https://github.com/user-attachments/assets/65ec7da5-fb1f-4718-a2ec-c55b4b0bca30)

**Comment by tore-statsig** [comment]
@jtwillis92 can you link the gate in question

**Comment by tore-statsig** [comment]
I found it.  If you go to the gate > diagnostics and toggle "non production logs" you will see this:

![Screenshot 2024-12-06 at 11 31 48 AM](https://github.com/user-attachments/assets/c3e0ca8b-d8a8-4b3b-af94-705e35417a92)

On the logs I see 
```
  "statsigEnvironment": {
    "tier": "development"
  }
  ```
  
  But the key is tied to "dev" not "development"
  
  ```
  SDK KEY ENVIRONMENTS
["dev"]
```

**Comment by jtwillis92** [comment]
@tore-statsig thank you! With that info we were able to get our SDK calls working - we just needed to use a custom string instead of the provided `StatsigEnvironmentTier` enum.

Really appreciate the quick response!

**Comment by tore-statsig** [comment]
Glad to hear it. Going to close out this issue
