### ISSUE TITLE
Feature request: public methods to get all configs and experiments distinctively

### ISSUE THREAD

**Issue by nrj** [statsig-io/python-sdk#5]
Hello, the way I'm using Statsig in summary is with a single dynamic "master" config and then I create experiments which are meant to change/override specific values in said master config.

Our client's apps all make a request to our servers for the master config and our python backend uses the results from `statsig.evaluate_all()` to construct a single config object. It does this by combining all the configs and experiments. However I only want experiment values to override the master config values and not the other way around, so I need to be able to distinguish which are dynamic configs and which are experiments.

It appears that dynamic configs have a rule_id matching the property name, whereas experiments have an alphanumeric ID. But this is not documented.
```
"dynamic_configs": {
    "master": {
        "value": {
            "foo": "bar"
        },
        "rule_id": "master"
    },
   "experiment_a": {
        "value": {
           "foo": "baz"
        },
        "rule_id": "53ju0lVMNHVpvM5jM1yrln"
     }
}
```
I could look for all configs != "master" or I could adopt a naming convention like "experiment_*" for experiments, but these solutions are error prone.

Would it be safe to assume that all configs with `rule_id != attribute_key` are experiments?

Ideally you could add public methods to get all configs and get all experiments.

**Comment by tore-statsig** [comment]
Hello!

Interesting use case.  I think you might be interested in our newly released Layer API.

Layers are a set of parameters which can have multiple experiments running concurrently.  Experiments will override the parameter values for users who are in the experiment.

In your code, you can just access the layer, and in the console you can configure which parameters are controlled by an experiment.  The SDK itself will handle all of the complexity of overriding parameters for active experiments

Check out https://docs.statsig.com/layers and the example here: https://docs.statsig.com/layers/js-tutorial

**Comment by tore-statsig** [comment]
What you are describing is exactly what a layer does.  Layer parameters exist outside of an experiment. You can set the value of a parameter at the layer level without ever running an experiment.  If you later decide you want to experiment with different values for a parameter, you can set up an experiment in that layer and run it, and then end the experiment and set the value to the winning variant.

**Comment by nrj** [comment]
Ok I see. I will take a closer look at layers. Thanks!

**Comment by tore-statsig** [comment]
Going to close this out for now as I think Layers sufficiently address the use case.  Feel free to comment back here if seems like you need this sort of api

**Comment by nrj** [comment]
Hello again, looking at the Layer class and it seems there is no `get_value()` unlike with configs.

It seems I have to request each key separately which doesn't work because the keys are unknown to our server. 

Currently the only way it seems to get all the object properties is via the private `.Layer__value` property.
